name: update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Update flake.lock
        id: update
        run: |
          nix flake update --commit-lock-file
          if [[ "$(git rev-parse origin/main)" != "$(git rev-parse main)" ]]; then
            updated=1
          else
            updated=0
          fi
          echo "updated=$updated" >> "$GITHUB_OUTPUT"
      - name: Lock backend
        if: steps.update.outputs.updated == '1'
        run: |
          env -i $(which nix) run .#lockBackend
          git add backend-gradle.lock
          git commit --amend --no-edit
      - name: Push
        if: steps.update.outputs.updated == '1'
        run: git push
